# Site settings
title: Perspective Taking MEG Analysis ABC
tag_text: 
description: A repository of Matlab scripts and tutorials describing the key MEG data analysis steps in perspective taking task

# Build settings
markdown: kramdown
sass:
  style: compressed
